package s3api

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/s3"
)

// S3API interface for S3
type S3API interface {
	AbortMultipartUploadRequest(input *s3.AbortMultipartUploadInput) (req *request.Request, output *s3.AbortMultipartUploadOutput)
	AbortMultipartUpload(input *s3.AbortMultipartUploadInput) (*s3.AbortMultipartUploadOutput, error)
	AbortMultipartUploadWithContext(ctx aws.Context, input *s3.AbortMultipartUploadInput, opts ...request.Option) (*s3.AbortMultipartUploadOutput, error)
	CompleteMultipartUploadRequest(input *s3.CompleteMultipartUploadInput) (req *request.Request, output *s3.CompleteMultipartUploadOutput)
	CompleteMultipartUpload(input *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error)
	CompleteMultipartUploadWithContext(ctx aws.Context, input *s3.CompleteMultipartUploadInput, opts ...request.Option) (*s3.CompleteMultipartUploadOutput, error)
	CopyObjectRequest(input *s3.CopyObjectInput) (req *request.Request, output *s3.CopyObjectOutput)
	CopyObject(input *s3.CopyObjectInput) (*s3.CopyObjectOutput, error)
	CopyObjectWithContext(ctx aws.Context, input *s3.CopyObjectInput, opts ...request.Option) (*s3.CopyObjectOutput, error)
	CreateBucketRequest(input *s3.CreateBucketInput) (req *request.Request, output *s3.CreateBucketOutput)
	CreateBucket(input *s3.CreateBucketInput) (*s3.CreateBucketOutput, error)
	CreateBucketWithContext(ctx aws.Context, input *s3.CreateBucketInput, opts ...request.Option) (*s3.CreateBucketOutput, error)
	CreateMultipartUploadRequest(input *s3.CreateMultipartUploadInput) (req *request.Request, output *s3.CreateMultipartUploadOutput)
	CreateMultipartUpload(input *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error)
	CreateMultipartUploadWithContext(ctx aws.Context, input *s3.CreateMultipartUploadInput, opts ...request.Option) (*s3.CreateMultipartUploadOutput, error)
	DeleteBucketRequest(input *s3.DeleteBucketInput) (req *request.Request, output *s3.DeleteBucketOutput)
	DeleteBucket(input *s3.DeleteBucketInput) (*s3.DeleteBucketOutput, error)
	DeleteBucketWithContext(ctx aws.Context, input *s3.DeleteBucketInput, opts ...request.Option) (*s3.DeleteBucketOutput, error)
	DeleteBucketAnalyticsConfigurationRequest(input *s3.DeleteBucketAnalyticsConfigurationInput) (req *request.Request, output *s3.DeleteBucketAnalyticsConfigurationOutput)
	DeleteBucketAnalyticsConfiguration(input *s3.DeleteBucketAnalyticsConfigurationInput) (*s3.DeleteBucketAnalyticsConfigurationOutput, error)
	DeleteBucketAnalyticsConfigurationWithContext(ctx aws.Context, input *s3.DeleteBucketAnalyticsConfigurationInput, opts ...request.Option) (*s3.DeleteBucketAnalyticsConfigurationOutput, error)
	DeleteBucketCorsRequest(input *s3.DeleteBucketCorsInput) (req *request.Request, output *s3.DeleteBucketCorsOutput)
	DeleteBucketCors(input *s3.DeleteBucketCorsInput) (*s3.DeleteBucketCorsOutput, error)
	DeleteBucketCorsWithContext(ctx aws.Context, input *s3.DeleteBucketCorsInput, opts ...request.Option) (*s3.DeleteBucketCorsOutput, error)
	DeleteBucketEncryptionRequest(input *s3.DeleteBucketEncryptionInput) (req *request.Request, output *s3.DeleteBucketEncryptionOutput)
	DeleteBucketEncryption(input *s3.DeleteBucketEncryptionInput) (*s3.DeleteBucketEncryptionOutput, error)
	DeleteBucketEncryptionWithContext(ctx aws.Context, input *s3.DeleteBucketEncryptionInput, opts ...request.Option) (*s3.DeleteBucketEncryptionOutput, error)
	DeleteBucketInventoryConfigurationRequest(input *s3.DeleteBucketInventoryConfigurationInput) (req *request.Request, output *s3.DeleteBucketInventoryConfigurationOutput)
	DeleteBucketInventoryConfiguration(input *s3.DeleteBucketInventoryConfigurationInput) (*s3.DeleteBucketInventoryConfigurationOutput, error)
	DeleteBucketInventoryConfigurationWithContext(ctx aws.Context, input *s3.DeleteBucketInventoryConfigurationInput, opts ...request.Option) (*s3.DeleteBucketInventoryConfigurationOutput, error)
	DeleteBucketLifecycleRequest(input *s3.DeleteBucketLifecycleInput) (req *request.Request, output *s3.DeleteBucketLifecycleOutput)
	DeleteBucketLifecycle(input *s3.DeleteBucketLifecycleInput) (*s3.DeleteBucketLifecycleOutput, error)
	DeleteBucketLifecycleWithContext(ctx aws.Context, input *s3.DeleteBucketLifecycleInput, opts ...request.Option) (*s3.DeleteBucketLifecycleOutput, error)
	DeleteBucketMetricsConfigurationRequest(input *s3.DeleteBucketMetricsConfigurationInput) (req *request.Request, output *s3.DeleteBucketMetricsConfigurationOutput)
	DeleteBucketMetricsConfiguration(input *s3.DeleteBucketMetricsConfigurationInput) (*s3.DeleteBucketMetricsConfigurationOutput, error)
	DeleteBucketMetricsConfigurationWithContext(ctx aws.Context, input *s3.DeleteBucketMetricsConfigurationInput, opts ...request.Option) (*s3.DeleteBucketMetricsConfigurationOutput, error)
	DeleteBucketPolicyRequest(input *s3.DeleteBucketPolicyInput) (req *request.Request, output *s3.DeleteBucketPolicyOutput)
	DeleteBucketPolicy(input *s3.DeleteBucketPolicyInput) (*s3.DeleteBucketPolicyOutput, error)
	DeleteBucketPolicyWithContext(ctx aws.Context, input *s3.DeleteBucketPolicyInput, opts ...request.Option) (*s3.DeleteBucketPolicyOutput, error)
	DeleteBucketReplicationRequest(input *s3.DeleteBucketReplicationInput) (req *request.Request, output *s3.DeleteBucketReplicationOutput)
	DeleteBucketReplication(input *s3.DeleteBucketReplicationInput) (*s3.DeleteBucketReplicationOutput, error)
	DeleteBucketReplicationWithContext(ctx aws.Context, input *s3.DeleteBucketReplicationInput, opts ...request.Option) (*s3.DeleteBucketReplicationOutput, error)
	DeleteBucketTaggingRequest(input *s3.DeleteBucketTaggingInput) (req *request.Request, output *s3.DeleteBucketTaggingOutput)
	DeleteBucketTagging(input *s3.DeleteBucketTaggingInput) (*s3.DeleteBucketTaggingOutput, error)
	DeleteBucketTaggingWithContext(ctx aws.Context, input *s3.DeleteBucketTaggingInput, opts ...request.Option) (*s3.DeleteBucketTaggingOutput, error)
	DeleteBucketWebsiteRequest(input *s3.DeleteBucketWebsiteInput) (req *request.Request, output *s3.DeleteBucketWebsiteOutput)
	DeleteBucketWebsite(input *s3.DeleteBucketWebsiteInput) (*s3.DeleteBucketWebsiteOutput, error)
	DeleteBucketWebsiteWithContext(ctx aws.Context, input *s3.DeleteBucketWebsiteInput, opts ...request.Option) (*s3.DeleteBucketWebsiteOutput, error)
	DeleteObjectRequest(input *s3.DeleteObjectInput) (req *request.Request, output *s3.DeleteObjectOutput)
	DeleteObject(input *s3.DeleteObjectInput) (*s3.DeleteObjectOutput, error)
	DeleteObjectWithContext(ctx aws.Context, input *s3.DeleteObjectInput, opts ...request.Option) (*s3.DeleteObjectOutput, error)
	DeleteObjectTaggingRequest(input *s3.DeleteObjectTaggingInput) (req *request.Request, output *s3.DeleteObjectTaggingOutput)
	DeleteObjectTagging(input *s3.DeleteObjectTaggingInput) (*s3.DeleteObjectTaggingOutput, error)
	DeleteObjectTaggingWithContext(ctx aws.Context, input *s3.DeleteObjectTaggingInput, opts ...request.Option) (*s3.DeleteObjectTaggingOutput, error)
	DeleteObjectsRequest(input *s3.DeleteObjectsInput) (req *request.Request, output *s3.DeleteObjectsOutput)
	DeleteObjects(input *s3.DeleteObjectsInput) (*s3.DeleteObjectsOutput, error)
	DeleteObjectsWithContext(ctx aws.Context, input *s3.DeleteObjectsInput, opts ...request.Option) (*s3.DeleteObjectsOutput, error)
	DeletePublicAccessBlockRequest(input *s3.DeletePublicAccessBlockInput) (req *request.Request, output *s3.DeletePublicAccessBlockOutput)
	DeletePublicAccessBlock(input *s3.DeletePublicAccessBlockInput) (*s3.DeletePublicAccessBlockOutput, error)
	DeletePublicAccessBlockWithContext(ctx aws.Context, input *s3.DeletePublicAccessBlockInput, opts ...request.Option) (*s3.DeletePublicAccessBlockOutput, error)
	GetBucketAccelerateConfigurationRequest(input *s3.GetBucketAccelerateConfigurationInput) (req *request.Request, output *s3.GetBucketAccelerateConfigurationOutput)
	GetBucketAccelerateConfiguration(input *s3.GetBucketAccelerateConfigurationInput) (*s3.GetBucketAccelerateConfigurationOutput, error)
	GetBucketAccelerateConfigurationWithContext(ctx aws.Context, input *s3.GetBucketAccelerateConfigurationInput, opts ...request.Option) (*s3.GetBucketAccelerateConfigurationOutput, error)
	GetBucketAclRequest(input *s3.GetBucketAclInput) (req *request.Request, output *s3.GetBucketAclOutput)
	GetBucketAcl(input *s3.GetBucketAclInput) (*s3.GetBucketAclOutput, error)
	GetBucketAclWithContext(ctx aws.Context, input *s3.GetBucketAclInput, opts ...request.Option) (*s3.GetBucketAclOutput, error)
	GetBucketAnalyticsConfigurationRequest(input *s3.GetBucketAnalyticsConfigurationInput) (req *request.Request, output *s3.GetBucketAnalyticsConfigurationOutput)
	GetBucketAnalyticsConfiguration(input *s3.GetBucketAnalyticsConfigurationInput) (*s3.GetBucketAnalyticsConfigurationOutput, error)
	GetBucketAnalyticsConfigurationWithContext(ctx aws.Context, input *s3.GetBucketAnalyticsConfigurationInput, opts ...request.Option) (*s3.GetBucketAnalyticsConfigurationOutput, error)
	GetBucketCorsRequest(input *s3.GetBucketCorsInput) (req *request.Request, output *s3.GetBucketCorsOutput)
	GetBucketCors(input *s3.GetBucketCorsInput) (*s3.GetBucketCorsOutput, error)
	GetBucketCorsWithContext(ctx aws.Context, input *s3.GetBucketCorsInput, opts ...request.Option) (*s3.GetBucketCorsOutput, error)
	GetBucketEncryptionRequest(input *s3.GetBucketEncryptionInput) (req *request.Request, output *s3.GetBucketEncryptionOutput)
	GetBucketEncryption(input *s3.GetBucketEncryptionInput) (*s3.GetBucketEncryptionOutput, error)
	GetBucketEncryptionWithContext(ctx aws.Context, input *s3.GetBucketEncryptionInput, opts ...request.Option) (*s3.GetBucketEncryptionOutput, error)
	GetBucketInventoryConfigurationRequest(input *s3.GetBucketInventoryConfigurationInput) (req *request.Request, output *s3.GetBucketInventoryConfigurationOutput)
	GetBucketInventoryConfiguration(input *s3.GetBucketInventoryConfigurationInput) (*s3.GetBucketInventoryConfigurationOutput, error)
	GetBucketInventoryConfigurationWithContext(ctx aws.Context, input *s3.GetBucketInventoryConfigurationInput, opts ...request.Option) (*s3.GetBucketInventoryConfigurationOutput, error)
	GetBucketLifecycleRequest(input *s3.GetBucketLifecycleInput) (req *request.Request, output *s3.GetBucketLifecycleOutput)
	GetBucketLifecycle(input *s3.GetBucketLifecycleInput) (*s3.GetBucketLifecycleOutput, error)
	GetBucketLifecycleWithContext(ctx aws.Context, input *s3.GetBucketLifecycleInput, opts ...request.Option) (*s3.GetBucketLifecycleOutput, error)
	GetBucketLifecycleConfigurationRequest(input *s3.GetBucketLifecycleConfigurationInput) (req *request.Request, output *s3.GetBucketLifecycleConfigurationOutput)
	GetBucketLifecycleConfiguration(input *s3.GetBucketLifecycleConfigurationInput) (*s3.GetBucketLifecycleConfigurationOutput, error)
	GetBucketLifecycleConfigurationWithContext(ctx aws.Context, input *s3.GetBucketLifecycleConfigurationInput, opts ...request.Option) (*s3.GetBucketLifecycleConfigurationOutput, error)
	GetBucketLocationRequest(input *s3.GetBucketLocationInput) (req *request.Request, output *s3.GetBucketLocationOutput)
	GetBucketLocation(input *s3.GetBucketLocationInput) (*s3.GetBucketLocationOutput, error)
	GetBucketLocationWithContext(ctx aws.Context, input *s3.GetBucketLocationInput, opts ...request.Option) (*s3.GetBucketLocationOutput, error)
	GetBucketLoggingRequest(input *s3.GetBucketLoggingInput) (req *request.Request, output *s3.GetBucketLoggingOutput)
	GetBucketLogging(input *s3.GetBucketLoggingInput) (*s3.GetBucketLoggingOutput, error)
	GetBucketLoggingWithContext(ctx aws.Context, input *s3.GetBucketLoggingInput, opts ...request.Option) (*s3.GetBucketLoggingOutput, error)
	GetBucketMetricsConfigurationRequest(input *s3.GetBucketMetricsConfigurationInput) (req *request.Request, output *s3.GetBucketMetricsConfigurationOutput)
	GetBucketMetricsConfiguration(input *s3.GetBucketMetricsConfigurationInput) (*s3.GetBucketMetricsConfigurationOutput, error)
	GetBucketMetricsConfigurationWithContext(ctx aws.Context, input *s3.GetBucketMetricsConfigurationInput, opts ...request.Option) (*s3.GetBucketMetricsConfigurationOutput, error)
	GetBucketNotificationRequest(input *s3.GetBucketNotificationConfigurationRequest) (req *request.Request, output *s3.NotificationConfigurationDeprecated)
	GetBucketNotification(input *s3.GetBucketNotificationConfigurationRequest) (*s3.NotificationConfigurationDeprecated, error)
	GetBucketNotificationWithContext(ctx aws.Context, input *s3.GetBucketNotificationConfigurationRequest, opts ...request.Option) (*s3.NotificationConfigurationDeprecated, error)
	GetBucketNotificationConfigurationRequest(input *s3.GetBucketNotificationConfigurationRequest) (req *request.Request, output *s3.NotificationConfiguration)
	GetBucketNotificationConfiguration(input *s3.GetBucketNotificationConfigurationRequest) (*s3.NotificationConfiguration, error)
	GetBucketNotificationConfigurationWithContext(ctx aws.Context, input *s3.GetBucketNotificationConfigurationRequest, opts ...request.Option) (*s3.NotificationConfiguration, error)
	GetBucketPolicyRequest(input *s3.GetBucketPolicyInput) (req *request.Request, output *s3.GetBucketPolicyOutput)
	GetBucketPolicy(input *s3.GetBucketPolicyInput) (*s3.GetBucketPolicyOutput, error)
	GetBucketPolicyWithContext(ctx aws.Context, input *s3.GetBucketPolicyInput, opts ...request.Option) (*s3.GetBucketPolicyOutput, error)
	GetBucketPolicyStatusRequest(input *s3.GetBucketPolicyStatusInput) (req *request.Request, output *s3.GetBucketPolicyStatusOutput)
	GetBucketPolicyStatus(input *s3.GetBucketPolicyStatusInput) (*s3.GetBucketPolicyStatusOutput, error)
	GetBucketPolicyStatusWithContext(ctx aws.Context, input *s3.GetBucketPolicyStatusInput, opts ...request.Option) (*s3.GetBucketPolicyStatusOutput, error)
	GetBucketReplicationRequest(input *s3.GetBucketReplicationInput) (req *request.Request, output *s3.GetBucketReplicationOutput)
	GetBucketReplication(input *s3.GetBucketReplicationInput) (*s3.GetBucketReplicationOutput, error)
	GetBucketReplicationWithContext(ctx aws.Context, input *s3.GetBucketReplicationInput, opts ...request.Option) (*s3.GetBucketReplicationOutput, error)
	GetBucketRequestPaymentRequest(input *s3.GetBucketRequestPaymentInput) (req *request.Request, output *s3.GetBucketRequestPaymentOutput)
	GetBucketRequestPayment(input *s3.GetBucketRequestPaymentInput) (*s3.GetBucketRequestPaymentOutput, error)
	GetBucketRequestPaymentWithContext(ctx aws.Context, input *s3.GetBucketRequestPaymentInput, opts ...request.Option) (*s3.GetBucketRequestPaymentOutput, error)
	GetBucketTaggingRequest(input *s3.GetBucketTaggingInput) (req *request.Request, output *s3.GetBucketTaggingOutput)
	GetBucketTagging(input *s3.GetBucketTaggingInput) (*s3.GetBucketTaggingOutput, error)
	GetBucketTaggingWithContext(ctx aws.Context, input *s3.GetBucketTaggingInput, opts ...request.Option) (*s3.GetBucketTaggingOutput, error)
	GetBucketVersioningRequest(input *s3.GetBucketVersioningInput) (req *request.Request, output *s3.GetBucketVersioningOutput)
	GetBucketVersioning(input *s3.GetBucketVersioningInput) (*s3.GetBucketVersioningOutput, error)
	GetBucketVersioningWithContext(ctx aws.Context, input *s3.GetBucketVersioningInput, opts ...request.Option) (*s3.GetBucketVersioningOutput, error)
	GetBucketWebsiteRequest(input *s3.GetBucketWebsiteInput) (req *request.Request, output *s3.GetBucketWebsiteOutput)
	GetBucketWebsite(input *s3.GetBucketWebsiteInput) (*s3.GetBucketWebsiteOutput, error)
	GetBucketWebsiteWithContext(ctx aws.Context, input *s3.GetBucketWebsiteInput, opts ...request.Option) (*s3.GetBucketWebsiteOutput, error)
	GetObjectRequest(input *s3.GetObjectInput) (req *request.Request, output *s3.GetObjectOutput)
	GetObject(input *s3.GetObjectInput) (*s3.GetObjectOutput, error)
	GetObjectWithContext(ctx aws.Context, input *s3.GetObjectInput, opts ...request.Option) (*s3.GetObjectOutput, error)
	GetObjectAclRequest(input *s3.GetObjectAclInput) (req *request.Request, output *s3.GetObjectAclOutput)
	GetObjectAcl(input *s3.GetObjectAclInput) (*s3.GetObjectAclOutput, error)
	GetObjectAclWithContext(ctx aws.Context, input *s3.GetObjectAclInput, opts ...request.Option) (*s3.GetObjectAclOutput, error)
	GetObjectLegalHoldRequest(input *s3.GetObjectLegalHoldInput) (req *request.Request, output *s3.GetObjectLegalHoldOutput)
	GetObjectLegalHold(input *s3.GetObjectLegalHoldInput) (*s3.GetObjectLegalHoldOutput, error)
	GetObjectLegalHoldWithContext(ctx aws.Context, input *s3.GetObjectLegalHoldInput, opts ...request.Option) (*s3.GetObjectLegalHoldOutput, error)
	GetObjectLockConfigurationRequest(input *s3.GetObjectLockConfigurationInput) (req *request.Request, output *s3.GetObjectLockConfigurationOutput)
	GetObjectLockConfiguration(input *s3.GetObjectLockConfigurationInput) (*s3.GetObjectLockConfigurationOutput, error)
	GetObjectLockConfigurationWithContext(ctx aws.Context, input *s3.GetObjectLockConfigurationInput, opts ...request.Option) (*s3.GetObjectLockConfigurationOutput, error)
	GetObjectRetentionRequest(input *s3.GetObjectRetentionInput) (req *request.Request, output *s3.GetObjectRetentionOutput)
	GetObjectRetention(input *s3.GetObjectRetentionInput) (*s3.GetObjectRetentionOutput, error)
	GetObjectRetentionWithContext(ctx aws.Context, input *s3.GetObjectRetentionInput, opts ...request.Option) (*s3.GetObjectRetentionOutput, error)
	GetObjectTaggingRequest(input *s3.GetObjectTaggingInput) (req *request.Request, output *s3.GetObjectTaggingOutput)
	GetObjectTagging(input *s3.GetObjectTaggingInput) (*s3.GetObjectTaggingOutput, error)
	GetObjectTaggingWithContext(ctx aws.Context, input *s3.GetObjectTaggingInput, opts ...request.Option) (*s3.GetObjectTaggingOutput, error)
	GetObjectTorrentRequest(input *s3.GetObjectTorrentInput) (req *request.Request, output *s3.GetObjectTorrentOutput)
	GetObjectTorrent(input *s3.GetObjectTorrentInput) (*s3.GetObjectTorrentOutput, error)
	GetObjectTorrentWithContext(ctx aws.Context, input *s3.GetObjectTorrentInput, opts ...request.Option) (*s3.GetObjectTorrentOutput, error)
	GetPublicAccessBlockRequest(input *s3.GetPublicAccessBlockInput) (req *request.Request, output *s3.GetPublicAccessBlockOutput)
	GetPublicAccessBlock(input *s3.GetPublicAccessBlockInput) (*s3.GetPublicAccessBlockOutput, error)
	GetPublicAccessBlockWithContext(ctx aws.Context, input *s3.GetPublicAccessBlockInput, opts ...request.Option) (*s3.GetPublicAccessBlockOutput, error)
	HeadBucketRequest(input *s3.HeadBucketInput) (req *request.Request, output *s3.HeadBucketOutput)
	HeadBucket(input *s3.HeadBucketInput) (*s3.HeadBucketOutput, error)
	HeadBucketWithContext(ctx aws.Context, input *s3.HeadBucketInput, opts ...request.Option) (*s3.HeadBucketOutput, error)
	HeadObjectRequest(input *s3.HeadObjectInput) (req *request.Request, output *s3.HeadObjectOutput)
	HeadObject(input *s3.HeadObjectInput) (*s3.HeadObjectOutput, error)
	HeadObjectWithContext(ctx aws.Context, input *s3.HeadObjectInput, opts ...request.Option) (*s3.HeadObjectOutput, error)
	ListBucketAnalyticsConfigurationsRequest(input *s3.ListBucketAnalyticsConfigurationsInput) (req *request.Request, output *s3.ListBucketAnalyticsConfigurationsOutput)
	ListBucketAnalyticsConfigurations(input *s3.ListBucketAnalyticsConfigurationsInput) (*s3.ListBucketAnalyticsConfigurationsOutput, error)
	ListBucketAnalyticsConfigurationsWithContext(ctx aws.Context, input *s3.ListBucketAnalyticsConfigurationsInput, opts ...request.Option) (*s3.ListBucketAnalyticsConfigurationsOutput, error)
	ListBucketInventoryConfigurationsRequest(input *s3.ListBucketInventoryConfigurationsInput) (req *request.Request, output *s3.ListBucketInventoryConfigurationsOutput)
	ListBucketInventoryConfigurations(input *s3.ListBucketInventoryConfigurationsInput) (*s3.ListBucketInventoryConfigurationsOutput, error)
	ListBucketInventoryConfigurationsWithContext(ctx aws.Context, input *s3.ListBucketInventoryConfigurationsInput, opts ...request.Option) (*s3.ListBucketInventoryConfigurationsOutput, error)
	ListBucketMetricsConfigurationsRequest(input *s3.ListBucketMetricsConfigurationsInput) (req *request.Request, output *s3.ListBucketMetricsConfigurationsOutput)
	ListBucketMetricsConfigurations(input *s3.ListBucketMetricsConfigurationsInput) (*s3.ListBucketMetricsConfigurationsOutput, error)
	ListBucketMetricsConfigurationsWithContext(ctx aws.Context, input *s3.ListBucketMetricsConfigurationsInput, opts ...request.Option) (*s3.ListBucketMetricsConfigurationsOutput, error)
	ListBucketsRequest(input *s3.ListBucketsInput) (req *request.Request, output *s3.ListBucketsOutput)
	ListBuckets(input *s3.ListBucketsInput) (*s3.ListBucketsOutput, error)
	ListBucketsWithContext(ctx aws.Context, input *s3.ListBucketsInput, opts ...request.Option) (*s3.ListBucketsOutput, error)
	ListMultipartUploadsRequest(input *s3.ListMultipartUploadsInput) (req *request.Request, output *s3.ListMultipartUploadsOutput)
	ListMultipartUploads(input *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error)
	ListMultipartUploadsWithContext(ctx aws.Context, input *s3.ListMultipartUploadsInput, opts ...request.Option) (*s3.ListMultipartUploadsOutput, error)
	ListMultipartUploadsPages(input *s3.ListMultipartUploadsInput, fn func(*s3.ListMultipartUploadsOutput, bool) bool) error
	ListMultipartUploadsPagesWithContext(ctx aws.Context, input *s3.ListMultipartUploadsInput, fn func(*s3.ListMultipartUploadsOutput, bool) bool, opts ...request.Option) error
	ListObjectVersionsRequest(input *s3.ListObjectVersionsInput) (req *request.Request, output *s3.ListObjectVersionsOutput)
	ListObjectVersions(input *s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error)
	ListObjectVersionsWithContext(ctx aws.Context, input *s3.ListObjectVersionsInput, opts ...request.Option) (*s3.ListObjectVersionsOutput, error)
	ListObjectVersionsPages(input *s3.ListObjectVersionsInput, fn func(*s3.ListObjectVersionsOutput, bool) bool) error
	ListObjectVersionsPagesWithContext(ctx aws.Context, input *s3.ListObjectVersionsInput, fn func(*s3.ListObjectVersionsOutput, bool) bool, opts ...request.Option) error
	ListObjectsRequest(input *s3.ListObjectsInput) (req *request.Request, output *s3.ListObjectsOutput)
	ListObjects(input *s3.ListObjectsInput) (*s3.ListObjectsOutput, error)
	ListObjectsWithContext(ctx aws.Context, input *s3.ListObjectsInput, opts ...request.Option) (*s3.ListObjectsOutput, error)
	ListObjectsPages(input *s3.ListObjectsInput, fn func(*s3.ListObjectsOutput, bool) bool) error
	ListObjectsPagesWithContext(ctx aws.Context, input *s3.ListObjectsInput, fn func(*s3.ListObjectsOutput, bool) bool, opts ...request.Option) error
	ListObjectsV2Request(input *s3.ListObjectsV2Input) (req *request.Request, output *s3.ListObjectsV2Output)
	ListObjectsV2(input *s3.ListObjectsV2Input) (*s3.ListObjectsV2Output, error)
	ListObjectsV2WithContext(ctx aws.Context, input *s3.ListObjectsV2Input, opts ...request.Option) (*s3.ListObjectsV2Output, error)
	ListObjectsV2Pages(input *s3.ListObjectsV2Input, fn func(*s3.ListObjectsV2Output, bool) bool) error
	ListObjectsV2PagesWithContext(ctx aws.Context, input *s3.ListObjectsV2Input, fn func(*s3.ListObjectsV2Output, bool) bool, opts ...request.Option) error
	ListPartsRequest(input *s3.ListPartsInput) (req *request.Request, output *s3.ListPartsOutput)
	ListParts(input *s3.ListPartsInput) (*s3.ListPartsOutput, error)
	ListPartsWithContext(ctx aws.Context, input *s3.ListPartsInput, opts ...request.Option) (*s3.ListPartsOutput, error)
	ListPartsPages(input *s3.ListPartsInput, fn func(*s3.ListPartsOutput, bool) bool) error
	ListPartsPagesWithContext(ctx aws.Context, input *s3.ListPartsInput, fn func(*s3.ListPartsOutput, bool) bool, opts ...request.Option) error
	PutBucketAccelerateConfigurationRequest(input *s3.PutBucketAccelerateConfigurationInput) (req *request.Request, output *s3.PutBucketAccelerateConfigurationOutput)
	PutBucketAccelerateConfiguration(input *s3.PutBucketAccelerateConfigurationInput) (*s3.PutBucketAccelerateConfigurationOutput, error)
	PutBucketAccelerateConfigurationWithContext(ctx aws.Context, input *s3.PutBucketAccelerateConfigurationInput, opts ...request.Option) (*s3.PutBucketAccelerateConfigurationOutput, error)
	PutBucketAclRequest(input *s3.PutBucketAclInput) (req *request.Request, output *s3.PutBucketAclOutput)
	PutBucketAcl(input *s3.PutBucketAclInput) (*s3.PutBucketAclOutput, error)
	PutBucketAclWithContext(ctx aws.Context, input *s3.PutBucketAclInput, opts ...request.Option) (*s3.PutBucketAclOutput, error)
	PutBucketAnalyticsConfigurationRequest(input *s3.PutBucketAnalyticsConfigurationInput) (req *request.Request, output *s3.PutBucketAnalyticsConfigurationOutput)
	PutBucketAnalyticsConfiguration(input *s3.PutBucketAnalyticsConfigurationInput) (*s3.PutBucketAnalyticsConfigurationOutput, error)
	PutBucketAnalyticsConfigurationWithContext(ctx aws.Context, input *s3.PutBucketAnalyticsConfigurationInput, opts ...request.Option) (*s3.PutBucketAnalyticsConfigurationOutput, error)
	PutBucketCorsRequest(input *s3.PutBucketCorsInput) (req *request.Request, output *s3.PutBucketCorsOutput)
	PutBucketCors(input *s3.PutBucketCorsInput) (*s3.PutBucketCorsOutput, error)
	PutBucketCorsWithContext(ctx aws.Context, input *s3.PutBucketCorsInput, opts ...request.Option) (*s3.PutBucketCorsOutput, error)
	PutBucketEncryptionRequest(input *s3.PutBucketEncryptionInput) (req *request.Request, output *s3.PutBucketEncryptionOutput)
	PutBucketEncryption(input *s3.PutBucketEncryptionInput) (*s3.PutBucketEncryptionOutput, error)
	PutBucketEncryptionWithContext(ctx aws.Context, input *s3.PutBucketEncryptionInput, opts ...request.Option) (*s3.PutBucketEncryptionOutput, error)
	PutBucketInventoryConfigurationRequest(input *s3.PutBucketInventoryConfigurationInput) (req *request.Request, output *s3.PutBucketInventoryConfigurationOutput)
	PutBucketInventoryConfiguration(input *s3.PutBucketInventoryConfigurationInput) (*s3.PutBucketInventoryConfigurationOutput, error)
	PutBucketInventoryConfigurationWithContext(ctx aws.Context, input *s3.PutBucketInventoryConfigurationInput, opts ...request.Option) (*s3.PutBucketInventoryConfigurationOutput, error)
	PutBucketLifecycleRequest(input *s3.PutBucketLifecycleInput) (req *request.Request, output *s3.PutBucketLifecycleOutput)
	PutBucketLifecycle(input *s3.PutBucketLifecycleInput) (*s3.PutBucketLifecycleOutput, error)
	PutBucketLifecycleWithContext(ctx aws.Context, input *s3.PutBucketLifecycleInput, opts ...request.Option) (*s3.PutBucketLifecycleOutput, error)
	PutBucketLifecycleConfigurationRequest(input *s3.PutBucketLifecycleConfigurationInput) (req *request.Request, output *s3.PutBucketLifecycleConfigurationOutput)
	PutBucketLifecycleConfiguration(input *s3.PutBucketLifecycleConfigurationInput) (*s3.PutBucketLifecycleConfigurationOutput, error)
	PutBucketLifecycleConfigurationWithContext(ctx aws.Context, input *s3.PutBucketLifecycleConfigurationInput, opts ...request.Option) (*s3.PutBucketLifecycleConfigurationOutput, error)
	PutBucketLoggingRequest(input *s3.PutBucketLoggingInput) (req *request.Request, output *s3.PutBucketLoggingOutput)
	PutBucketLogging(input *s3.PutBucketLoggingInput) (*s3.PutBucketLoggingOutput, error)
	PutBucketLoggingWithContext(ctx aws.Context, input *s3.PutBucketLoggingInput, opts ...request.Option) (*s3.PutBucketLoggingOutput, error)
	PutBucketMetricsConfigurationRequest(input *s3.PutBucketMetricsConfigurationInput) (req *request.Request, output *s3.PutBucketMetricsConfigurationOutput)
	PutBucketMetricsConfiguration(input *s3.PutBucketMetricsConfigurationInput) (*s3.PutBucketMetricsConfigurationOutput, error)
	PutBucketMetricsConfigurationWithContext(ctx aws.Context, input *s3.PutBucketMetricsConfigurationInput, opts ...request.Option) (*s3.PutBucketMetricsConfigurationOutput, error)
	PutBucketNotificationRequest(input *s3.PutBucketNotificationInput) (req *request.Request, output *s3.PutBucketNotificationOutput)
	PutBucketNotification(input *s3.PutBucketNotificationInput) (*s3.PutBucketNotificationOutput, error)
	PutBucketNotificationWithContext(ctx aws.Context, input *s3.PutBucketNotificationInput, opts ...request.Option) (*s3.PutBucketNotificationOutput, error)
	PutBucketNotificationConfigurationRequest(input *s3.PutBucketNotificationConfigurationInput) (req *request.Request, output *s3.PutBucketNotificationConfigurationOutput)
	PutBucketNotificationConfiguration(input *s3.PutBucketNotificationConfigurationInput) (*s3.PutBucketNotificationConfigurationOutput, error)
	PutBucketNotificationConfigurationWithContext(ctx aws.Context, input *s3.PutBucketNotificationConfigurationInput, opts ...request.Option) (*s3.PutBucketNotificationConfigurationOutput, error)
	PutBucketPolicyRequest(input *s3.PutBucketPolicyInput) (req *request.Request, output *s3.PutBucketPolicyOutput)
	PutBucketPolicy(input *s3.PutBucketPolicyInput) (*s3.PutBucketPolicyOutput, error)
	PutBucketPolicyWithContext(ctx aws.Context, input *s3.PutBucketPolicyInput, opts ...request.Option) (*s3.PutBucketPolicyOutput, error)
	PutBucketReplicationRequest(input *s3.PutBucketReplicationInput) (req *request.Request, output *s3.PutBucketReplicationOutput)
	PutBucketReplication(input *s3.PutBucketReplicationInput) (*s3.PutBucketReplicationOutput, error)
	PutBucketReplicationWithContext(ctx aws.Context, input *s3.PutBucketReplicationInput, opts ...request.Option) (*s3.PutBucketReplicationOutput, error)
	PutBucketRequestPaymentRequest(input *s3.PutBucketRequestPaymentInput) (req *request.Request, output *s3.PutBucketRequestPaymentOutput)
	PutBucketRequestPayment(input *s3.PutBucketRequestPaymentInput) (*s3.PutBucketRequestPaymentOutput, error)
	PutBucketRequestPaymentWithContext(ctx aws.Context, input *s3.PutBucketRequestPaymentInput, opts ...request.Option) (*s3.PutBucketRequestPaymentOutput, error)
	PutBucketTaggingRequest(input *s3.PutBucketTaggingInput) (req *request.Request, output *s3.PutBucketTaggingOutput)
	PutBucketTagging(input *s3.PutBucketTaggingInput) (*s3.PutBucketTaggingOutput, error)
	PutBucketTaggingWithContext(ctx aws.Context, input *s3.PutBucketTaggingInput, opts ...request.Option) (*s3.PutBucketTaggingOutput, error)
	PutBucketVersioningRequest(input *s3.PutBucketVersioningInput) (req *request.Request, output *s3.PutBucketVersioningOutput)
	PutBucketVersioning(input *s3.PutBucketVersioningInput) (*s3.PutBucketVersioningOutput, error)
	PutBucketVersioningWithContext(ctx aws.Context, input *s3.PutBucketVersioningInput, opts ...request.Option) (*s3.PutBucketVersioningOutput, error)
	PutBucketWebsiteRequest(input *s3.PutBucketWebsiteInput) (req *request.Request, output *s3.PutBucketWebsiteOutput)
	PutBucketWebsite(input *s3.PutBucketWebsiteInput) (*s3.PutBucketWebsiteOutput, error)
	PutBucketWebsiteWithContext(ctx aws.Context, input *s3.PutBucketWebsiteInput, opts ...request.Option) (*s3.PutBucketWebsiteOutput, error)
	PutObjectRequest(input *s3.PutObjectInput) (req *request.Request, output *s3.PutObjectOutput)
	PutObject(input *s3.PutObjectInput) (*s3.PutObjectOutput, error)
	PutObjectWithContext(ctx aws.Context, input *s3.PutObjectInput, opts ...request.Option) (*s3.PutObjectOutput, error)
	PutObjectAclRequest(input *s3.PutObjectAclInput) (req *request.Request, output *s3.PutObjectAclOutput)
	PutObjectAcl(input *s3.PutObjectAclInput) (*s3.PutObjectAclOutput, error)
	PutObjectAclWithContext(ctx aws.Context, input *s3.PutObjectAclInput, opts ...request.Option) (*s3.PutObjectAclOutput, error)
	PutObjectLegalHoldRequest(input *s3.PutObjectLegalHoldInput) (req *request.Request, output *s3.PutObjectLegalHoldOutput)
	PutObjectLegalHold(input *s3.PutObjectLegalHoldInput) (*s3.PutObjectLegalHoldOutput, error)
	PutObjectLegalHoldWithContext(ctx aws.Context, input *s3.PutObjectLegalHoldInput, opts ...request.Option) (*s3.PutObjectLegalHoldOutput, error)
	PutObjectLockConfigurationRequest(input *s3.PutObjectLockConfigurationInput) (req *request.Request, output *s3.PutObjectLockConfigurationOutput)
	PutObjectLockConfiguration(input *s3.PutObjectLockConfigurationInput) (*s3.PutObjectLockConfigurationOutput, error)
	PutObjectLockConfigurationWithContext(ctx aws.Context, input *s3.PutObjectLockConfigurationInput, opts ...request.Option) (*s3.PutObjectLockConfigurationOutput, error)
	PutObjectRetentionRequest(input *s3.PutObjectRetentionInput) (req *request.Request, output *s3.PutObjectRetentionOutput)
	PutObjectRetention(input *s3.PutObjectRetentionInput) (*s3.PutObjectRetentionOutput, error)
	PutObjectRetentionWithContext(ctx aws.Context, input *s3.PutObjectRetentionInput, opts ...request.Option) (*s3.PutObjectRetentionOutput, error)
	PutObjectTaggingRequest(input *s3.PutObjectTaggingInput) (req *request.Request, output *s3.PutObjectTaggingOutput)
	PutObjectTagging(input *s3.PutObjectTaggingInput) (*s3.PutObjectTaggingOutput, error)
	PutObjectTaggingWithContext(ctx aws.Context, input *s3.PutObjectTaggingInput, opts ...request.Option) (*s3.PutObjectTaggingOutput, error)
	PutPublicAccessBlockRequest(input *s3.PutPublicAccessBlockInput) (req *request.Request, output *s3.PutPublicAccessBlockOutput)
	PutPublicAccessBlock(input *s3.PutPublicAccessBlockInput) (*s3.PutPublicAccessBlockOutput, error)
	PutPublicAccessBlockWithContext(ctx aws.Context, input *s3.PutPublicAccessBlockInput, opts ...request.Option) (*s3.PutPublicAccessBlockOutput, error)
	RestoreObjectRequest(input *s3.RestoreObjectInput) (req *request.Request, output *s3.RestoreObjectOutput)
	RestoreObject(input *s3.RestoreObjectInput) (*s3.RestoreObjectOutput, error)
	RestoreObjectWithContext(ctx aws.Context, input *s3.RestoreObjectInput, opts ...request.Option) (*s3.RestoreObjectOutput, error)
	SelectObjectContentRequest(input *s3.SelectObjectContentInput) (req *request.Request, output *s3.SelectObjectContentOutput)
	SelectObjectContent(input *s3.SelectObjectContentInput) (*s3.SelectObjectContentOutput, error)
	SelectObjectContentWithContext(ctx aws.Context, input *s3.SelectObjectContentInput, opts ...request.Option) (*s3.SelectObjectContentOutput, error)
	UploadPartRequest(input *s3.UploadPartInput) (req *request.Request, output *s3.UploadPartOutput)
	UploadPart(input *s3.UploadPartInput) (*s3.UploadPartOutput, error)
	UploadPartWithContext(ctx aws.Context, input *s3.UploadPartInput, opts ...request.Option) (*s3.UploadPartOutput, error)
	UploadPartCopyRequest(input *s3.UploadPartCopyInput) (req *request.Request, output *s3.UploadPartCopyOutput)
	UploadPartCopy(input *s3.UploadPartCopyInput) (*s3.UploadPartCopyOutput, error)
	UploadPartCopyWithContext(ctx aws.Context, input *s3.UploadPartCopyInput, opts ...request.Option) (*s3.UploadPartCopyOutput, error)
}
